route:
  receiver: 'alertmanager-bot'
  group_by: ['alertname']
  group_wait: 10s
  group_interval: 5m
  repeat_interval: 3h

receivers:
- name: 'alertmanager-bot'
  webhook_configs:
  - url: 'http://alertmanager-bot:8080'
    send_resolved: true
